import 'package:flutter/material.dart';
class AppColors {
  static Color primaryColor = const Color(0xFF9796F0);
  static Color pullToRefreshText = const Color(0xFF0862BC);
  static Color pullToRefreshTextBackground = const Color(0xFFECF6FE);
  static Color bottomfoldbglight = const Color.fromRGBO(52, 52, 52, 1);
  static Color bottomfoldbgdark = const Color.fromRGBO(32, 38, 50, 1);
  static Color kPureWhite = const Color(0xFFFFFFFF);
  static Color kPureBlack = const Color(0xFF202020);
  static Color kGrey = const Color(0xFF808080);
  static Color screenerbg = const Color(0xFF363636);
  static Color lightBlue = const Color(0xFF99CCFF);
  static Color lightGrey = const Color(0xFFE5E5E5);
  static Color blue = const Color(0xFF0862BC);
  static Color backGroundGrey = const Color(0xFFBCBCBC);
  static Color labelBlack = const Color(0xFF414141);
  static Color errorRed = const Color(0xFFEB4E2C);
  static Color borderBlueColor = const Color(0xFF8EC8F7);
  static Color fadedBlue = const Color(0xFFEFF6FF);
  static Color textGrey = const Color(0xFF9D9D9D);
  static Color elevationColors = const Color(0xFFA6A6A6);
  static Color elevationColors2 = const Color(0xFFd5d5d5);
  static Color textGreen = const Color(0xFF26A649);
  static Color spacerColor = const Color(0xFFBCBCBC);
  static Color textBlue = const Color(0xFF0863BD);
  static Color lightGreen = const Color(0xFFC5E7C8);
  static Color subtitleGrey = const Color(0xFF747474);
  static Color shadowGrey = const Color(0xFF576675);
  static Color neutralGrey = const Color(0xFF606060);
  static Color dividerColor = const Color(0xFFF3F3F3);
  static Color borderLightBlueColor = const Color(0xFFBADDFA);
  static Color lightBackgroundColor = const Color(0xFFF5F5F5);
  static Color neutral200 = const Color(0xFFEDEDED);
  static Color neutral300 = const Color(0xFFDFDFDF);
  static Color neutral50 = const Color(0xFFFCFCFC);
  static Color primaryBlue900 = const Color(0xFF00439D);
  static Color navyBlueLight = const Color(0xFFE7F8FF);
  static Color greyNeutral = const Color(0xFFDFDFDF);
  static Color gradientLightBlue = const Color(0xFF61B2F3);
  static Color portfolioButtonColor = const Color(0xFf00439D);
  static Color darkColor = const Color(0xFF424242);
  static Color searchTextColor = const Color(0xFF979797);
  static Color orangeColor = const Color(0xFFF5775C);
  static Color yellowColor = const Color(0xFFFFB133);
  static Color bluelightColor = const Color(0xFFDFEDFF);
  static Color greenBackGroundColor = const Color(0xFF25D366);
  static Color whiteTextColor = const Color(0xFFF7F7F7);
  static Color greyDarkBackgroundColor = const Color(0xFFECECEC);
  static Color lightBlackColor = const Color(0xFF8A8A8A);
  static Color redBackgroundColor = const Color(0xFFB43C30);
  static Color yellowBackgroundColor = const Color(0xFFE8B640);
  static Color alertColor = const Color(0xFFFFF9F0);
  static Color blueAlertColor = const Color(0xFFECF6FE);
  static Color appBarShadowColor = const Color.fromRGBO(106, 115, 129, 0.12);
  static Color blueHistoryColor = const Color(0xFFDBEFFF);
  static Color blueTradeCardBackgroundColor = const Color(0xFFD9ECFC);
  static Color pnlPercentageRed = const Color(0xFFE21717);
  static Color pnlPercentageGreen = const Color(0xFF049312);
  static Color activeTradeCardGreen = const Color(0xFF148F36);
  static Color waitingTradeCardYellow = const Color(0xFFEF9400);
  static Color portfolioShowSellStocksCardBgColor = const Color(0xFFFCF1CF);
  static Color upiBackgroundLightGreenColor = const Color(0xFFEBF1ED);
  static Color fadedBackgroundRedColor = const Color(0xFFFFF7F5);
  static Color fadedBackgroundGreenColor = const Color(0xFFFAFFFB);
  static Color chatFloatingButtonColor = const Color(0XFFE1EEFF);
  static Color viewallgradient1 = const Color(0XFFE1F1FF);
  static Color calculateYourRewardWidgetGradient1 = const Color(0XFF343434);
  static Color calculateYourRewardWidgetGradient2 = const Color(0XFF202632);
  static Color calculateYourRewardBackground = const Color(0XFF484848);
  static Color fadedOrangeBackground = const Color(0xFFFFE0AD);
  static Color borderDarkBlueColor = const Color(0xFFD5E9FB);
  static Color feedbackStarFilledColor = const Color(0xFFF8BF62);
  static Color targetGreenColor = const Color(0xFFEBFFEF);
  static Color backgroundColor = const Color(0xFFFAFAFA);
  static Color purpleColor = const Color(0xFF9796F0);
  static Color lightPurple = const Color(0xFFF6F2FE);
  static Color yellow = const Color(0xFFFFE600);
  static Color orangeBorderColor = const Color(0xFFF09436);
  static Color orangeTextColor = const Color(0xFF98520B);
  static Color blueBorderColor = const Color(0xFFBACCE4);
  static Color lightGreenBorderColor = const Color(0xFFBFDADA);
  static Color lightGreenTextColor = const Color(0xFF005251);
  static Color lightPurpleTextColor = const Color(0xFF84026F);
  static Color blackShadeColor = const Color(0xFF292929);
  static Color greenHitColor = const Color(0xFF5ED400);
  static Color redMissColor = const Color(0xFFE8004D);
  static Color highlightWidgetColor = const Color(0xFFFFF0D6);
  static Color fadedRedColor = const Color(0xFFF8EDEC);
  static Color fadedGradientColor = const Color(0xFFF4F1E9);
  static Color fadedGradientColor2 = const Color(0xFFE7EAF8);
  static Color fadedYellowColor = const Color(0xFFFFFDF1);
  static Color darkGradientColor1 = const Color(0xFF141E30);
  static Color darkGradientColor2 = const Color(0xFF333333);
  static Color darkGradientColor3 = const Color(0xFF243B55);
  static Color orangeGradientColor1 = const Color(0xffF69723);
  static Color orangeGradientColor2 = const Color(0xffE75325);
  static Color borderColorHistory = const Color(0xffCEE9FF);
  static Color tableBorderColor = const Color(0xffC4E1F4);
  static Color indianIndexBackColor = const Color(0xff264A73);
  static Color globalIndexBackColor = const Color(0xff26736E);

  static Color whatsAppGreenColor = const Color(0xff68C05F);
  static Color verifyGreenColor = const Color(0xff33A34D);
  static Color limeGreenColor = const Color(0xffEBFEE4);

  static Color lightBlueGradient1 = const Color(0xFFEEF6FF);
  static Color lightBlueGradient2 = const Color(0xFFE7F0FD);

  static Color goldenGradientGradient1 = const Color(0xFFFFA82B);
  static Color goldenGradientGradient2 = const Color(0xFFFFB633);
  static Color goldenGradientGradient3 = const Color(0xFFFFCA3F);

  static Color goldenColor = const Color(0xFFFE9923);

  static Color lightYellow = const Color(0xFFFFCC70);
  static Color lightPink = const Color(0xFFC850C0);
  static Color lightBlueGradient = const Color(0xFF4158D0);

  static Color redNotificationColor = const Color(0XFFED2F05);
  static Color redGradientColor = const Color(0XFFB62404);

  static Color lightGradient1 = const Color(0xFFF5F1E8);
  static Color lightGradient2 = const Color(0xFFE7EBF9);

  static Color primary600 = const Color(0XFF1285E1);
  static Color primary50 = const Color(0XFFECF6FE);
  static Color toastBg = const Color(0XFFD8FFD1);
  static Color success600 = const Color(0XFF148F36);

  static Color proPlusGradient1 = const Color(0XFF9D6BE9);
  static Color proPlusGradient2 = const Color(0XFF3E45B3);
  static Color orangeProColor = const Color(0XFFFF8415);
  static Color purpleProPlusColor = const Color(0XFFBB9BE2);
  static Color blueFadedColor = const Color(0XFFECF6FE);
  static Color purpleFadedColor = const Color(0XFF8F67E0);
  static Color purpleFadedShimmerColor = const Color(0XFFE3D9F7);
  static Color fadedPurpleLightColor = const Color(0XFFE1E1F3);
  static Color purpleToggleColor = const Color(0XFF7C7CCB);
  static Color orangeButtonColor = const Color(0XFFFFB133);
  static Color lightGradientColorBluish = const Color(0XFFD7E4F4);
  static Color lightGradientColorBluish2 = const Color(0XFFC7DAF2);
  static Color darkGradientBorderColor = const Color(0XFF141E30);
  static Color proPlusPurpleColor = const Color(0xFF3D45B2);
  static Color brownColor = const Color(0xFF5C3900);
  static Color purpleGradientColor = const Color(0xFF3C305F);
  static Color highlightedFadedOrangeColor = const Color(0xFFFFC970);
  static Color highlightedFadedPurpleColor = const Color(0xFFD3C3FF);
  static Color verdictOrangeFaded = const Color(0xFFFFEAB2);
  static Color yellowHighlightColor = const Color(0xFFFFCC00);
  static Color backgroundYellowColor = const Color(0xFFFFF4D8);
  static Color lightGreyColor = const Color(0xFFF9F9F9);
  static Color blueGradientColor = const Color(0xFFD1E6FF);
  static Color lightOrangeBackGround = const Color(0xFFF8EAC8);
  static Color alphaGradientColor = const Color(0xFFEE6982);
  static Color alphaGradientColor2 = const Color(0xFFAF2B82);
  static Color superGradient = const Color(0xFF4AB8AB);
  static Color superGradient2 = const Color(0xFF187157);
  static Color proAlphaGradient = const Color(0xFFe65fb4);
  static Color proAlphaGradient2 = const Color(0xFFaf2b82);
  static Color proAlphaSelectBack = const Color(0xFFd996c2);
  static Color proPlusSelectBack = const Color(0xFF8555cc);
  static Color proSuperSelectBack = const Color(0xFF40aa9a);
  static Color proPlusSelectBackColor = const Color(0xFFFFCB40);

  static Color greenBgLightColor = const Color(0xFFF6F6F6);
  static Color greenDarkBgLightColor = const Color(0xFFD9F2DF);
  static Color billDetailsBg = const Color(0xFFFFF7ED);
  static Color transferColor = const Color.fromARGB(11, 255, 255, 255);
  static Color proBlueBorderColor = const Color(0xFF1A6F9E);
  static Color proPurpleBorderColor = const Color(0xFF9a50d4);
  static Color fadedPinkColor = const Color(0xFFFFECF0);
  static Color pinkColor = const Color(0xFFFF9595);
  static Color greenSuperColor = const Color(0xFF89DBB8);
  static Color fadedGreenSuperColor = const Color(0xFFDEF5ED);
  static Color darkBrownColor = const Color(0xFF5F3038);
  static Color darkGreenColor = const Color(0xFF153D2A);
  static Color gradientProFadedColor = const Color(0xFFFFEFC4);
  static Color gradientProPlusFadedColor = const Color(0xFFF1E8FF);
  static Color gradientProAlphaFadedColor = const Color(0xFFFFF0F0);
  static Color gradientProSuperFadedColor = const Color(0xFFEBFFFA);
  static Color gradientColor2 = const Color(0xFF2c2f32);
  static Color blueColor = const Color(0xFF498BF7);

  static Color blueGradient = const Color(0xFFFAFCFF);
  static Color blueGradient2 = const Color(0xFFE7F2FF);
  static Color playButtonColor = const Color(0xFF141E30);
  static Color ipoVerdictCardBorderYellowColor = const Color.fromRGBO(239, 148, 0, 1);
  static Color ipoLevelGreenColor = const Color.fromRGBO(20, 143, 54, 1);
  static Color ipoTableHeadingColor = const Color.fromRGBO(13, 115, 206, 1);
  static Color ipoLightTableHeadingColor = const Color.fromRGBO(13, 115, 206, 0.5);
  static Color ipoVeryLightblueColor = const Color.fromRGBO(236, 246, 254, 1);
  static Color sharksListBorderColorGrey = const Color.fromRGBO(223, 223, 223, 1);
  static Color bluePrimary800 = const Color.fromRGBO(8, 98, 188, 1);
  static Color blackPrimary800 = const Color.fromRGBO(65, 65, 65, 1);
  static Color grey800= const Color.fromRGBO(188, 188, 188, 1);

  /// stocks Holdings Graph Color
  static Color graphDarkGreenColor = const Color.fromRGBO(0, 95, 115, 1);
  static Color graphLightGreenColor = const Color.fromRGBO(148, 210, 189, 1);
  static Color graphLightOrangeColor = const Color.fromRGBO(233, 216, 166, 1);
  static Color graphDarkOrangeColor = const Color.fromRGBO(238, 174, 54, 1);
  static Color graphDarkRedColor = const Color.fromRGBO(209, 100, 38, 1);
  static Color graphGreyColor = const Color.fromRGBO(211, 211, 211, 1);
  static Color greyNeutral600 = const Color.fromRGBO(116, 116, 116, 1);
  static Color greyNeutral700 = const Color.fromRGBO(96, 96, 96, 1);
  static Color whiteBackground =const Color.fromRGBO(252, 252, 252,1);
  static Color purpleGradientLight = const Color.fromRGBO(112, 110, 170, 1);
  static Color purpleGradientDark = const Color.fromRGBO(46, 56, 148, 1);
  static Color grey500 = const Color.fromRGBO(157, 157, 157, 1);


  static Color meterOrangeColors  = const Color(0XFFF07D19);
  static Color meterKnobColors = const Color(0XFF3D3854);
  static Color meterBackgroundColor = const Color(0XFF080226);
  static Color yellowMorningDigest = const Color(0XFFF6EACF);
  static Color blueMovers = const Color(0XFFF1F6F8);
  static Color blueShadeMovers = const Color(0XFFABC7ED);
  static Color blueShadeOptionChain = const Color(0XFFBFD8F9);
  static Color blueFll = const Color(0XFFF1F8F9);
  static Color blueShadeFll = const Color(0XFFBDCCDB);
  static Color mostActiveBackground = const Color(0XFFE9F2FF);
  static Color cupertinoBlue = const Color(0XFF0862BC);
  static Color screenerBoxYellow = const Color(0XFFE8BE2C);
  static Color screenerBoxPurple = const Color(0XFFA06ED1);
  static Color darkGradientColorValue  = const Color(0XFF332E4C);
  static Color shortTerm  = const Color(0XFF83190F);
  static Color mediumTerm  = const Color(0XFF002F6F);
  static Color longTerm  = const Color(0XFF002F6F);
  static Color optionTerm  = const Color(0XFFCF1D3D);
  static Color mcxTerm  = const Color(0XFF61400C);
  static Color futureTerm  = const Color(0XFF640254);
  static Color stockSummary  = const Color(0XFFFF9D44);
  static Color commoditySummary  = const Color(0XFFB9995B);
  static Color primary700  = const Color(0XFF0D73CE);
  static Color lightYellowSubscribeGradient = const Color.fromRGBO(255, 132, 21, 1);
  static Color darkYellowSubscribeGradient = const Color.fromRGBO(255, 202, 63, 1);
  static Color white300 = const Color.fromRGBO(223, 223, 223, 1);

  static Color exploreMenuButtonGradientColor1 = const Color(0XFFE4E2DE);
  static Color exploreMenuButtonGradientColor2 = const Color(0XFFE4EDF7);
  static Color explorePastTradeCountCardColor1 = const Color(0XFF1A379E);
  static Color explorePastTradeCountCardColor2 = const Color(0XFFC379FE);
  static Color dividerVeryLightBlueColor = const Color.fromRGBO(186, 221, 250, 1);
  static Color borderBlurRadius = const Color(0XFF6A7381);
  static Color tradeBoardShadowColor = const Color.fromRGBO(208, 211, 215, 1);
  static Color googleBackground = const Color.fromRGBO(73, 139, 247, 1);
  static Color orderPageBackgroundColor = const Color.fromRGBO(242, 242, 242, 1);
  static Color orderVeryLightBlueBackgroundColor = const Color.fromRGBO(236, 246, 254, 1);
  static Color marketDepthRedColor = const Color.fromRGBO(250, 230, 223, 1);
  static Color marketGreenColor = const Color.fromRGBO(220, 237, 231, 1);
  static Color marketNoteVeryLightRed = const Color.fromRGBO(255, 247, 245, 1);
  static Color basketLightYellowColor = const Color.fromRGBO(242, 184, 7, 0.25);
  static Color veryLightFreyBackGround = const Color.fromRGBO(245, 245, 245, 1);
  static Color green_250_255_251_1 = const Color.fromRGBO(250,255,251,1);
  static Color green_38_166_73_1 = const Color.fromRGBO(38,166,73,1);
  static Color yellow_239_148_0_1 = const Color.fromRGBO(239,148,0,1);
  static Color lightYellow_239_148_0_1 = const Color.fromRGBO(255, 239, 214, 1);
  static Color veryLightGreenGradient = const Color.fromRGBO(251, 255, 239, 1);
  static Color commodityDarkBrownColor = const Color.fromRGBO(92, 57, 0, 1);
  static Color commoditYellowishBrownColor = const Color.fromRGBO(255, 201, 112, 1);
  static Color commodityLightBrownColor = const Color.fromRGBO(255, 224, 173, 1);
  static Color commodityyellowishWhite = const Color.fromRGBO(255, 249, 240, 1);
  static Color commodity_163_101_0_1 =const Color.fromRGBO(163,101,0,1);
  static Color greenCheckBoxColor =const Color.fromRGBO(62,189,97,1);






}


